### ISSUE TITLE
Incorrect rc.conf script

### ISSUE THREAD

**Issue by gcebollero** [Thefrank/jellyfin-server-freebsd#1]
Hi Frank! 
First of all, thank you for  your amazing job!

I have tried to install the .txz package on a FreeBSD 12.2 jail but it seems to not work properly.

Every time I tried to start the service, this error appears:
`root@jellyfin:~ # sysrc jellyfin-server_enable=YES
jellyfin-server_enable: server_enable -> server_enable
root@jellyfin:~ # service jellyfin-server start
/etc/rc.conf: jellyfin-server_enable=YES: not found
/etc/rc.conf: jellyfin-server_enable=YES: not found
/usr/local/etc/rc.d/jellyfin-server: WARNING: $jellyfin-server_enable is not set properly - see rc.conf(5).
Cannot 'start' jellyfin-server. Set jellyfin-server_enable to YES in /etc/rc.conf or use 'onestart' instead of 'start'.`

Also, the name function seems to be incorrect!
`start_precmd=${name}_precmd
radarr_precmd() {
`

After renaming the vars to "jellyfinserver" and change the name function to "jellyfinserver_precmd" it still seems to not work properly.

What I am missing?

**Comment by Thefrank** [comment]
The `-` can be problematic which is something I forgot about!  It also looks like I accidently packaged my intermediary rc file that was based on my `radarr` package. It also does not have some other things that I added later

I will repackage the installer (txz) and get that posted. it might be a day as I want to make sure the extra features I added don't cause additional problems

finally,
you will also need to manually make a `jellyfin` user and group (as FreeBSD does not currently reserve a UID/GID for that)
alternatively you can change those variables in rc file

**Comment by Thefrank** [comment]
@gcebollero I have gone ahead and updated the installable package.
Please `pkg remove jellyfin-server` also remove any `jellyfin-server` entries in `/etc/rc.conf`
This actually changes the package and service name so it will be under `jellyfinserver` now

**Comment by gcebollero** [comment]
Hi @Thefrank 
Thanks for the quick update!
This time worked like a charm! The new version is up and running without any problems!

You rocks man! I think we can close this issue.

PS: I had the jellyfin user & group from my previous installation.

**Comment by Thefrank** [comment]
Excellent! I will close this out.
