### ISSUE TITLE
FreeBSD guide

### ISSUE THREAD

**Issue by devmsv** [Thefrank/jellyfin-server-freebsd#10]
You state on TRUENAS guide "If you are installing from base FreeBSD there is a different guide for that!"

¿Is that guide somewhere?
At least for he jail part as I'm new to that.

Regards,

**Comment by Thefrank** [comment]
I had planned to make one for base FreeBSD users but never had the time to cover all the different jail managers that can be used.

Generally, for the jail:

Required:
 - Unprivileged mlock (usually allow_mlock=1, allow.mlock=1, or security.bsd.unprivileged_mlock: 1)
 - At least one of:
   - VNET (usually, vnet=1 or security.jail.vnet: 1)
   - ip6=inherit (or ip6=new)

Suggested:
 - raw sockets (usually allow_raw_sockets=1 or security.jail.allow_raw_sockets: 1) 

I will also update the guide to include a few details for FreeBSD users.

**Comment by Thefrank** [comment]
Mostly(?) resolved by changes in guide
