### ISSUE TITLE
"System.Net.Http.HttpRequestException: Protocol not supported" for HTTPS requests to online data sources

### ISSUE THREAD

**Issue by darkuranium** [Thefrank/jellyfin-server-freebsd#16]
There seems to be a problem with accessing any HTTPS data source (such as api.themoviedb.org:443 or www.omdbapi.com:443), which means that Jellyfin is unable to fetch online info about movies (descriptions, images, etc).

I'm running this on "pure" FreeBSD (as opposed to TrueNAS), in a jail. The settings are all set as required:
- `allow_mlock=1`
- `allow_raw_sockets=1`
- `ip6=new`

Am I missing something obvious here, or is this not supposed to work (*yet*, hopefully)?

Thanks!

## Jellyfin log:

(relevant excerpt; the same error happens with *all* HTTPS requests that Jellyfin makes)
```
[2022-04-13 16:48:56.575 +00:00] [ERR] [35] MediaBrowser.Providers.Movies.MovieMetadataService: Error in "TheMovieDb"
System.Net.Http.HttpRequestException: Protocol not supported (api.themoviedb.org:443)
 ---> System.Net.Sockets.SocketException (43): Protocol not supported
[...snip...]
```

## System information:

**`uname -a`:**
```
FreeBSD jellyfin 12.3-RELEASE-p5 FreeBSD 12.3-RELEASE-p5 GENERIC  amd64
```

**`freebsd-version`:**
```
12.3-RELEASE-p5
```

**Comment by darkuranium** [comment]
According to #4, VNET is supposed to be optional if `ip6=new` is set. But do I *need* VNET for fetching data?

**Comment by Thefrank** [comment]
VNET should not be required*, however, dotnet5/dotnet6 do have some quirks under FreeBSD when determining if it has a usable ipv6 stack via its dual-stack (ipv4/ipv6) tests and what jails are able to expose. You can try disabling ipv6 usage for jellyfin using dotnet's `DOTNET_SYSTEM_NET_DISABLEIPV6=1` environment var if you still want the jail to use ipv6 for other things. If you don't mind not having ipv6 in the jail you can disable ipv6 outright for the jail. Otherwise, give VNET a try, if it WORKS, then I will change the docs to reflect that it is required. If it IS required then it will need to be looked at if its something that is fixable via detection in upcoming versions of dotnet or if its something that FreeBSD might be able to expose to jails to make it easier for dotnet to check/test for before trying

*TRUENAS CORE users should use VNET when using ipv6 or dual-stack as the way that TrueNAS makes jails breaks things like DHCPv6 (https://jira.ixsystems.com/browse/NAS-114755)

**Comment by darkuranium** [comment]
I've disabled ipv6 in the jail (and the rc.d script seems to handle `DOTNET_SYSTEM_NET_DISABLEIPV6=1` for me in this case). Unfortunately, it didn't help &mdash; same error.

It's very late, so I'll give VNET a go tomorrow (time permitting; otherwise, expect Saturday-ish). I first need to figure out how to enable it for the jail, as I've never used it (a simple `vnet=1` does not seem to work, as the jail then refuses to start).

**Comment by Thefrank** [comment]
from what I recall, `vnet` also needs `bpf=1` to start

**Comment by darkuranium** [comment]
Sorry about the delay. Still haven't managed to get VNET working with WAN/internet access (so I've been unable to test this as of yet); struggling to get that working.

**Comment by Thefrank** [comment]
what jail manager are you using? it might be easier to use that than trying to edit a config file on its own

**Comment by darkuranium** [comment]
`iocage`; and I *have* been using it, but to no avail. I can ping the jail from my system (even access Jellyfin from the 'net via the browser), but I can't for the life of me get *outgoing* internet access working with VNET.

My "usual" setup is the `lo1` approach, if you're familiar with it (basically, a `10.0.0.0/16` subnet, and I manually assign `lo1|10.0.x.y` IPs to jails &mdash; I need static IPs anyway, for reverse-proxy reasons).
Looks like this is a very hard thing to get done with VNET, because apparently, I'm not the only person who has tried this and failed &mdash; I've met some others in #freebsd on Libera who have tried a lo1+VNET approach (exact same setup as myself), and have given up on it.

Thanks for your help, by the way! As I've implied, I'm on Libera (same nickname as my GH username), in case you're there and would like to take things "offline" (as not to spam this issue with unrelated VNET support stuff).

**Comment by darkuranium** [comment]
@Thefrank Did some more attempts. Still no luck at getting VNET working at all. I'm almost ready to give up on that angle.

Honestly, I *strongly* suspect it's unlikely to help anyway.

Looks like I'm not the only person with this problem, this was the (only!) other result, in the related Emby project (using Google-cached version because the actual site wants login):
https://webcache.googleusercontent.com/search?q=cache:eh_G-Cb1wVIJ:https://emby.media/community/index.php%3F/topic/107661-emby-broken-apihttp-interface-calls/+

Alas, no answers at the time of the cache. Interestingly, that topic was posted *exactly a day* after my issue on GH.

**Comment by darkuranium** [comment]
@Thefrank ***I've got it.***

So I decided to make a throwaway account to see if there's any updated data on that page. And there is!

A suggested step in a linked thread worked: `ip6=inherit` jail setting (as opposed to `new`). So now it works as it should! I'll leave the ticket open, because I feel like you're better qualified to decide on what to do with it (I'd add this issue/solution to the docs, though).

Thanks for your help!

**Comment by Thefrank** [comment]
Good find! For that setting I am a bit confused as to why `ip6=new` fails but `ip6=inherit` works. The only documented difference between the two are how restricted the IPs are. 

This might end up as a source diving adventure to see how exactly dotnet is trying to make connection.

In the next few days I will update the documentation to better clarify that only `ip6=inherit` is valid for those using ipv6 in their jail

**Comment by Thefrank** [comment]
Updated documentation. Closing :)
