### ISSUE TITLE
10.8.0 final released

### ISSUE THREAD

**Issue by Sicer** [Thefrank/jellyfin-server-freebsd#18]
The release of the final version 10.8.0 has just been announced, would it be possible to update the packages?

Thank you!

**Comment by Thefrank** [comment]
I should be able to get something up in the next day or so. It will likely target FreeBSD 13.0+

**Comment by septarchy** [comment]
This would be marvelous! Thanks for your work :)

**Comment by Thefrank** [comment]
So good news/bad news:
Good news! It builds and runs.
Bad news! It is pretty useless because of:
```syslog
[13:58:52] [ERR] [31] Emby.Drawing.ImageProcessor: Error encoding image
System.TypeInitializationException: The type initializer for 'SkiaSharp.SKObject' threw an exception.
 ---> System.InvalidOperationException: The version of the native libSkiaSharp library (80.2) is incompatible with this version of SkiaSharp. Supported versions of the native libSkiaSharp library are in the range [88.0, 89.0).
```
This was painful to build the first time around but hopefully nothing significantly changed since.

**Comment by Thefrank** [comment]
https://github.com/Thefrank/jellyfin-server-freebsd/releases/tag/v10.8.0

No PKG version until I get my ports tree updated for 13/13.1. This should be before the weekend.
No custom FFMPEG that Jellyfin uses as I currently don't have the time to investigate it :(

Otherwise: Enjoy!

**Comment by septarchy** [comment]
Thanks for the update Thefrank.

What is the best practice to update? Would fetch and pkg install suffice? Can we install the ffmpeg package manually?

**Comment by Thefrank** [comment]
> What is the best practice to update? Would fetch and pkg install suffice? 

Yes that should be fine. Stop the service first if you are upgrading the package.

> Can we install the ffmpeg package manually?

It runs fine with the ports-version of FFMPEG and already uses it as a dependency. If you have your own version of FFMPEG that you use then you can tell jellyfinserver to use that instead. Check the RC file for more details on how to pass that information to it.

**Comment by Thefrank** [comment]
In other news: PKG is now up on the Releases page!

**Comment by septarchy** [comment]
Thank your Thefrank. It's up and running on freenas!

**Comment by Thefrank** [comment]
Resolved. Closing
