### ISSUE TITLE
instructions to install TrueNAS

### ISSUE THREAD

**Issue by Sicer** [Thefrank/jellyfin-server-freebsd#2]
Could some kind of instructions be created for the installation in a TrueNAS jail?

**Comment by Thefrank** [comment]
How detailed does it need to be? I know TrueNAS uses a plugin system which is pretty hands-off for the user if installing something from the WebGUI.

For FreeBSD the general summary is:
jail needs `allow_mlock=1` `allow_raw_sockets=1`
then from the jail `pkg install jellyfinserver-VERSION.NUMBER.txz`. The txz handles the dependencies using the pkg system.
The `pkg-message` gives a bit more detail on other things needed from there such as turning on the service and adding a user/group for jellyfin

So, would a more detailed version of the above work for TrueNAS users?

**Comment by brian91292** [comment]
Additionally, I had to run the following command to get jellyfin to start successfully:

`ln -s /usr/local/lib/libsqlite3.so /usr/local/lib/libe_sqlite3`

**Comment by Thefrank** [comment]
> Additionally, I had to run the following command to get jellyfin to start successfully:
> 
> `ln -s /usr/local/lib/libsqlite3.so /usr/local/lib/libe_sqlite3`

I am considering just bundling that in with jellyfin as it removes the need to make a symlink or even install that as a dependency

**Comment by Sicer** [comment]
> ¿Qué tan detallado tiene que ser? Sé que TrueNAS utiliza un sistema de plugins que es bastante práctico para el usuario si instala algo desde el WebGUI.
> 
> Para FreeBSD el resumen
> general
> es: necesidades de la cárcel y luego de la cárcel. El txz maneja las dependencias utilizando el sistema pkg.
> El da un poco más de detalle sobre otras cosas necesarias a partir de ahí, como encender el servicio y agregar un usuario/ grupo para jellyfin`allow_mlock=1``allow_raw_sockets=1``pkg install jellyfinserver-VERSION.NUMBER.txz``pkg-message`
> 
> Entonces, ¿funcionaría una versión más detallada de lo anterior para los usuarios de TrueNAS?

The TrueNAS plugin system has to be validated by IXSystem if I'm not mistaken, perhaps a list of how to create the jail and the necessary commands to run jellyfin server, something simple so that anyone knows how to run it.

**Comment by Thefrank** [comment]
I already did something similar for radarr 3.1:
https://www.truenas.com/community/threads/experimental-radarr-v3-1-dotnet5-binary.91489/
would something like that work or would it require more of a step-by-step guide?

Basically: I am trying to figure out how experienced users of TrueNAS are with setting up their own jail, downloading files from the internet into a jail, installing packages, and adding users to a jail.

A long example and explanation follows
------------------------------------------------

Here is what `pkg-message` gives when you install the package:
```
Jellyfin relies on Microsoft dotNET5+ SDK to be built
Microsoft does not have an official version of dotNET for FreeBSD

This package was built with an UNOFFICIAL UNSUPPORTED version of dotNET
If this is something that you do not want remove this package with
"pkg remove jellyfinserver"

This package creates a service. Use "sysrc jellyfinserver_enable=TRUE" to enable
Use "service jellyfinserver start" to start

NOTE: The service uses a user/group combination that is not created on install
YOU MUST manually create a "jellyfin" user/group or change what the service uses

If you are running this in a jail please set "allow_mlock=1" for this jail
otherwise the program will fail to start
```
The first two paragraphs are informational. The third covers the fact that a service file is installed with the package. The fourth paragraph will get removed if jellyfinserver gets added to the official ports system and is able to reserve is own UID/GID. The fifth is a reminder that if you are installing jellyfin into a jail that it needs to be able to `mlock`.

I am still debating if I want to package the sqlite lib with jellyfin, have the package make the symlink so the user does not need to, or add a line to the `pkg-message` telling users to make the symlink themselves.

**Comment by Sicer** [comment]
![image](https://user-images.githubusercontent.com/6973905/115137682-c8ebd700-a027-11eb-895b-22de5a96270f.png)

in my case, I can't install it giving me this error, I'm sure it's easy to fix it by changing the txz path, but surely the same thing will happen to many more people.

**Comment by Thefrank** [comment]
`pkg` can't use URLS
first
`fetch https://github.com/Thefrank/jellyfin-server-freebsd/releases/download/v10.7.2/jellyfinserver-10.7.2.txz`
then
`pkg install jellyfinserver-10.7.2.txz`

**Comment by Sicer** [comment]
I get this last error, which I suppose is because I have to create the jellyfin user, right?

![image](https://user-images.githubusercontent.com/6973905/115138457-9a242f80-a02c-11eb-908a-08768d57a011.png)

**Comment by Sicer** [comment]
I have already made it work, I think it would be interesting to create a guide in the readme.me so that everyone knows how to make it work:

1. create a Jail with the characteristics you want but activating these 2 options
![image](https://user-images.githubusercontent.com/6973905/115139280-4e27b980-a031-11eb-95fc-8895c30b84b6.png)

2. start the jail and by shell execute these commands:
fetch https://github.com/Thefrank/jellyfin-server-freebsd/releases/download/v10.7.2/jellyfinserver-10.7.2.txz
pkg install jellyfinserver-10.7.2.txz
(choose the version you want to install)

3. ln -s /usr/local/lib/libsqlite3.so /usr/local/lib/libe_sqlite3

4. sysrc jellyfinserver_enable=TRUE

5. Create user and group "jellyfin" or change user and group in:

"/usr/local/etc/rc.d/plexmediaserver" looking in the file for these 2 lines:

: ${jellyfinserver_user=”jellyfin”}
: ${jellyfinserver_group=”jellyfin”}

6. service jellyfinserver start

**Comment by Thefrank** [comment]
> 5. Create user and group "jellyfin" or change user and group in:
> 
> "/usr/local/etc/rc.d/jellyfinserver" looking in the file for these 2 lines:
> 
> : ${jellyfinserver_user=”jellyfin”}
> : ${jellyfinserver_group=”jellyfin”}

Please do not edit things in rc files. Those are the defaults and doing so will cause the package to fail `pkg check -s`. 
`sysrc` is what you should be using to change those.
`sysrc jellyfinserver_user="USER_YOU_WANT"`
`sysrc jellyfinserver_group="GROUP_YOU_WANT"`

Otherwise the rest is a good overview of what is required to setup and run jellyfin!

**Comment by Thefrank** [comment]
I added a short guide for installation under TrueNAS based on feedback and suggestions from above.

Let me know what you think
ping @Sicer @brian91292

**Comment by Sicer** [comment]
for my part, I see it perfect, very detailed and easy to follow who wants to install jellyfin in TrueNAS.

Another question, how stable this method, compared to an official method?

Thank You

**Comment by Thefrank** [comment]
what do you mean by "official method"? The TrueNAS plugin system?

**Comment by Sicer** [comment]
I was referring to official versions in linux, windows

I am testing the users and I am not able to start with the jellyfin user

![image](https://user-images.githubusercontent.com/6973905/115154503-74724700-a07b-11eb-8838-1f0302788d31.png)

both the user and the group are created

**Comment by brian91292** [comment]
> I was referring to official versions in linux, windows
> 
> I am testing the users and I am not able to start with the jellyfin user
> 
> ![image](https://user-images.githubusercontent.com/6973905/115154503-74724700-a07b-11eb-8838-1f0302788d31.png)
> 
> both the user and the group are created

The instructions I followed to get Jellyfin running successfully:
1. Begin by creating a new jail, then click on advanced jail creation
2. For name, choose `jellyfin` or something, change jail type to base jail, and choose release 12.2-RELEASE
3. Check DHCP, check auto-start if you want jellyfin to start when your truenas server starts up
4. Click on "Jail Properties" and check `allow_mlock` and `allow_raw_sockets`, then click save and wait for the jail to be created.
5. After the jail is created, run `fetch https://github.com/Thefrank/jellyfin-server-freebsd/releases/download/v10.7.2/jellyfinserver-10.7.2.txz`
6. Once the txz is downloaded, run `pkg install jellyfinserver-10.7.2.txz`
7. Create the jellyfin user/group with the following command: `pw user add jellyfin -c jellyfin -u 710 -d /nonexistent -s /usr/bin/nologin` (you can replace 710 with whatever user id you want to use for jellyfin)
8. Create a symlink to the sqlite3 lib with the following command: `ln -s /usr/local/lib/libsqlite3.so /usr/local/lib/libe_sqlite3`
9. Enable the jellyfinserver service: `sysrc jellyfinserver_enable="YES"`
10. Finally, run the jellyfinserver service: `service jellyfinserver start`

The service should start successfully now, and you should be able to access jellyfin via the web ui at https://[jellyfin ip]:8096.

Hopefully this helps!

**Comment by Thefrank** [comment]
> Create the jellyfin user/group with the following command: pw user add jellyfin -c jellyfin -u 710 -d /nonexistent -s /usr/bin/nologin (you can replace 710 with whatever user id you want to use for jellyfin, you'll also likely need to configure your storage pool permissions to allow access for this user)

would UID 710 work for jellyfin going forward? it does not appear taken right now: 

https://github.com/freebsd/freebsd-ports/blob/1c8ce0fb8ad179fc5b346e3cd92fa61798404132/UIDs#L658

would it be easier for people to just copy/paste the `pw` vs stepping through `adduser`?

> I was referring to official versions in linux, windows

This is an unofficial version and required a fair amount of work outside to get building (e.g., building dotnet5 and building Skia for FreeBSD) both of which are covered in the readme :)

**Comment by brian91292** [comment]
> > Create the jellyfin user/group with the following command: pw user add jellyfin -c jellyfin -u 710 -d /nonexistent -s /usr/bin/nologin (you can replace 710 with whatever user id you want to use for jellyfin, you'll also likely need to configure your storage pool permissions to allow access for this user)
> 
> would UID 710 work for jellyfin going forward? it does not appear taken right now:
> 
> https://github.com/freebsd/freebsd-ports/blob/1c8ce0fb8ad179fc5b346e3cd92fa61798404132/UIDs#L658
> 
> would it be easier for people to just copy/paste the `pw` vs stepping through `adduser`?
> 
> > I was referring to official versions in linux, windows
> 
> This is an unofficial version and required a fair amount of work outside to get building (e.g., building dotnet5 and building Skia for FreeBSD) both of which are covered in the readme :)

Not sure, to be honest I randomly picked that uid. If it's available, I'd say yes 👌 

I would say the `pw` command is more convenient than walking through `adduser`, I think it makes the most sense in this case as we're just creating a very generic user account to run Jellyfin under. I would consider myself to be a more advanced user, though, so that may not be the best approach for the majority of people.

**Comment by Thefrank** [comment]
Thinking over it a bit, a copy/paste will be easier for those without much shell experience. I will update the doc to use `pw` instead

**Comment by Thefrank** [comment]
Gonna leave this open for a few more days if anyone can think of other improvements/changes to the instructions, otherwise it seems good to close

ping: @Sicer @brian91292

**Comment by Sicer** [comment]
you can close, the instructions are clear
