### ISSUE TITLE
Jellyfin refuses to access media even though I have access through the shell

### ISSUE THREAD

**Issue by Drago245** [Thefrank/jellyfin-server-freebsd#23]
I'm not a pro so I apologize if this isn't the correct place to be asking such a question, but I'm having an issue. 

I installed jellyfin and followed the documentation on TrueNAS Core, and I'm able to start the service and access it from other devices, however Jellyfin doesn't want to access my media. I've allowed mount points and have configured the mount from my media location (~/MediaServer/Movies) to the destination that jellyfin reads (/mnt/Main/iocage/jails/Jellyfin/root/media) but Jellyfin doesn't find any media there when I try to refresh. 

I'm also not able to re-add that folder if I remove it. When trying to add the folder that is configured in the mount point, I get an error stating "The path could not be found. Please ensure the path is valid and try again."

I need to change the mount point to a different folder, then add the folder back in jellyfin, then change the mount point back. But then I still can't access my media in Jellyfin. The reason this confuses me is that if I use the Shell from the TrueNAS GUI, I'm able to cd into and ls the contents of all the folders. The jail obviously has access to these files, but Jellyfin isn't liking it. 

It seems like some kind of permission issue, but I don't know where to look. I followed the documentation and mounted the correct folders, so I'm not sure where I'm going wrong.

**Comment by Thefrank** [comment]
does the `jellyfin` UID/GID (user id/group id) have read access to the mount point and its files? 
(e.g., when doing an `ls -l` on your media mount point in the jail who does it say is the owning user and owning group?)

**Comment by Thefrank** [comment]
Over 90 days. Closing.
If you are still having issues feel free to reopen or start a new issue

**Comment by Stephen2** [comment]
Hey @Thefrank , btw thank you so much for this repo, and how you maintain it and help everybody, no matter how random the problems :pray:

**Comment by Drago245** [comment]
Hello,

I remember reading your reply before and being able to figure it out from it, but today I'm faced with the same issue and I cannot figure it out. 

Is there by chance reference documentation somewhere for a general way that this would be set up? I'm once again in the situation where if I navigate to Jails>Jellyfin>Shell, I'm able to cd to, see, and access the directories I'm looking for. When I click "Manage" from the plugin page, however, I'm told that the directory couldn't be found. 

I've been trying to change users for the mountpoints and jails, making sure they line up and have the same permissions, but I just can't get it. I can't access the folders via the GUI. 

I really appreciate all the work you're doing on this project.

**Comment by Thefrank** [comment]
If it is mounted in to the jail double check the permissions. Make sure that the user/group running `jellyfin` is a minimum a part of the group that has `r` (read) permissions of the files and `rx` of the directory

**Comment by Drago245** [comment]
Where does the GUI begin reading files?

For example, if I go to Jails>Jellyfin>Shell and type `cd /` and then `ls`, I can see the directories I've created there called "Movies" and "Shows," which I can then cd into and see all of the movies and shows because the mount point points to the correct location. 

When I go into the GUI, however, there's no way that I see to browse files, so I need to type in the directory that I'm pointing to (It seems like it's supposed to have a drop down menu, but it keeps disappearing for me). Does the GUI's filesystem start at "/"? Are these directories one level too high? Should I create them in "~" where the shell is by default when I open it?

I want to make sure I have these directories in an actually accessible location before puling my hair out diagnosing permissions. As far as I can tell, all the permissions and users match up, but I know they have to match in the jail, mountpoint, and overall system, so I could definitely be messing that up.

**Comment by Thefrank** [comment]
The GUI will only list things like pools under the "Storage" menu. If you want to see that from the console click "Shell" on the side menu in the GUI and then do `cd /mnt` which, if I remember, is where TrueNAS mounts pools by default.

**Comment by Drago245** [comment]
The Jellyfin GUI will only list pools in the storage menu? The deepest I can go in the TrueNAS GUI under Pools is Main>iocage>jails>jellyfin>root

My directories are located at Main>iocage>jails>jellyfin>root>Movies and Main>iocage>jails>jellyfin>root>Shows

Is this location accessible to the Jellyfin plugin from the GUI? Or should it be in the mnt folder listed under the specific plugin?

I know this is convoluted. I appreciate your help.

**Comment by Thefrank** [comment]
> Is this location accessible to the Jellyfin plugin from the Jellyfin GUI? Or should it be in the mnt folder listed under the specific plugin?

I assume that Jellyfin is installed into the `jellyfin` jail?
Jellyfin should be able to access it as long as it is a member of the group with `r`+`x` ownership access to those directories and `r` ownership access to the files. Those directories should appear as `/Movies` and `/Shows` in the jail.

**Comment by Drago245** [comment]
Thankyou! I got it!

I wasn't totally familiar with the syntax and ways of checking this, but after knowing what permissions they needed, I was able to do some searching and make the changes it needed. 

I really appreciate your help and all the work you do on this project. I use it all the time. Thanks so much!
