### ISSUE TITLE
Select server screen after upgrade

### ISSUE THREAD

**Issue by juanmartinbelda** [Thefrank/jellyfin-server-freebsd#24]
Hi! 

I'm trying to upgrade from version 10.7.7 to 10.8.X. The package seem to install OK but when I start the service again I'm prompted with the select server screen. 
Selecting the server does nothing. I think this might have to do with the RC variables mention in the note, where are these variables located?

Thanks in advanced!

**Comment by Thefrank** [comment]
If you want to see what your current (non-default) rc variables are you can use: `sysrc -a`

These are the defaults taken from the `jellyfinserver` rc file:
```
: ${jellyfinserver_enable:=NO}
: ${jellyfinserver_user:="jellyfinserver"}
: ${jellyfinserver_group:="jellyfinserver"}
: ${jellyfinserver_extraargs:=""}
: ${jellyfinserver_exec_dir:="/usr/local/jellyfinserver"}
: ${jellyfinserver_data_dir:="/var/db/jellyfinserver"}
: ${jellyfinserver_cache_dir:="/var/cache/jellyfinserver"}
```

you can change these with `sysrc VARIABLENAME="STRING"` (e.g., `sysrc jellyfinserver_enable="YES"`)

`/usr/local/etc/rc.d/jellyfinserver` explains the variables in more details and acceptable additional arguments that you might want to pass to it.

**Comment by juanmartinbelda** [comment]
Thanks for the quick response! 
The problem for me with `sysrc -a` was that it only shown the `jellyfinserver_enable="YES"` variable, but did not shown the variables within the `/usr/local/etc/rc.d/jellyfinserver` file.
I am going to try again watching this file and come back to close the issue

**Comment by juanmartinbelda** [comment]
Hi! 
Changing the variables with sysrc to the old values let me in the server agian. The problem is that, although the pkg has been upgraded correctly, the version in the GUI still shows 10.7.7

```
root@jellyfin:~ # pkg info jellyfinserver
jellyfinserver-10.8.3
Name           : jellyfinserver
Version        : 10.8.3
Installed on   : Sat Aug 13 09:36:09 2022 CEST
Origin         : multimedia/jellyfinserver
Architecture   : FreeBSD:13:amd64
Prefix         : /usr/local
Categories     : multimedia
Licenses       : GPLv2 or BSD3CLAUSE
Maintainer     : none@none.none
WWW            : https://jellyfin.org/
Comment        : Jellyfin Server Component with WebUI
```

This prevents the Android TV app to connect to the server, as it requires at minimum 10.8.1:

![image](https://user-images.githubusercontent.com/98739484/184475551-4a83856c-d470-40f7-84ad-5241cf92dfbf.png)

Android TV app showing the server as old version:
![signal-2022-08-13-102100](https://user-images.githubusercontent.com/98739484/184475682-5a27fbd6-66c4-4b3d-8818-c70062136c24.jpeg)

Any suggestions on what has happened?

**Comment by juanmartinbelda** [comment]
It has been solved! I am so stupid that changed the exec path to the old value, so it was starting the old instance... Thanks for the help!

**Comment by Thefrank** [comment]
There were no changes in the rc vars between 10.7.7 and 10.8.x. If you edited the rc file instead of using `sysrc` to change the variables then you will have a much harder time figuring out what changed. You can always try and use `find` to see where some of the files ended up (e,g., `network.xml` and `jellyfin.db` are data files and would be in `jellyfinserver_data_dir`)

**Comment by Thefrank** [comment]
Also: Glad you got everything figured out :D
