### ISSUE TITLE
Updating Jellyfin

### ISSUE THREAD

**Issue by septarchy** [Thefrank/jellyfin-server-freebsd#25]
Hello @Thefrank,

How hard is it to port the current version of jellyfin(jellyfin_10.8.4_amd64.tar.gz)? Is there some information how to port this yourself?

I don't want to keep asking you to dedicate your time to updating ;)

Much appreciated :)

**Comment by Thefrank** [comment]
It just needs a working dotNET SDK  for FreeBSD and the files for the port system (Makefile, pkg-plist, pkgdesc, rc file, etc).
That being said, I should have an updated pkg up (hopefully) before the weekend :)

**Comment by Thefrank** [comment]
https://github.com/Thefrank/jellyfin-server-freebsd/releases/tag/v10.8.4

Enjoy :D
