### ISSUE TITLE
Package for 10.8.7 release contains version claiming to be 10.9.0

### ISSUE THREAD

**Issue by michaelburton** [Thefrank/jellyfin-server-freebsd#31]
I have just upgraded from 10.8.5 to 10.8.7 using the pkg file posted a couple of hours ago. Now, when I visit the dashboard it says that I am running server version 10.9.0 and connecting from Jellyfin Web 10.9.0.

I have checked the upstream Jellyfin issues and don't see any reports of 10.8.7 returning the wrong version number.

```
$ curl https://redacted/system/info/public
{"LocalAddress":"https://redacted:443","ServerName":"My Server","Version":"10.9.0","ProductName":"Jellyfin Server","OperatingSystem":"BSD","Id":"redacted","StartupWizardCompleted":true}
```

**Comment by Thefrank** [comment]
It was built from v10.8.7 tags
```
Parent pipeline used these runtime parameters
jellyfinServer : "v10.8.7"
jellyfinWeb : "v10.8.7"
```
but it 100% checkedout head at a commit that is NOT in that tag:
```
git checkout --progress --force abcb1889167db788af94f2ede15327aa877d4004
```

As there is more than just a difference in version, I will get corrected one up soon.

Thanks for bringing this to my attention!

**Comment by Thefrank** [comment]
@michaelburton This should be fixed now

Now to build more checks to prevent this from happening again...
