### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by hoatz** [Thefrank/jellyfin-server-freebsd#34]
Thank you for your guide, worked perfectly!
Could you perhaps add a section for adding HTTPS on BSD?

For Linux heads like me stuck in a strange land.
Many thanks

**Comment by Thefrank** [comment]
HTTPS should work fine with Jellyfin under FreeBSD. Can you explain what you are trying to do or what issues you are running into?

**Comment by Thefrank** [comment]
@hoatz closing this.
If you are still having issues feel free to reopen
