### ISSUE TITLE
default username/password?

### ISSUE THREAD

**Issue by vongoethe** [Thefrank/jellyfin-server-freebsd#36]
I have successfully installed the jellyfin server.
But when I open ip:8096, it leads me to the login screen, and there's no default username/password prompt.
I tried many combinations and still no luck.
So what's the default username/password?
thanks

**Comment by Thefrank** [comment]
That should not be happening normally.
Clear any browser cache you might have of that IP.
If that does not resolve it then try browsing to `http://IP_OF_JELLYFIN_SERVER:8096/web/index.html#!/wizardstart.htm`

**Comment by vongoethe** [comment]
it reports 404 error
and I tried http://ip:port/web/index.html#!/wizardstart.html, and it leads to login screen again
how this happened...

**Comment by vongoethe** [comment]
I cleared the cookies and cache, and open the browser in private mode, still no luck.

**Comment by Thefrank** [comment]
If it is giving a 404 then 

 - something did not install correctly trying reinstall the pkg with `pkg install -f jellyfinserver-10.8.8.pkg`
 - bad jail configuration / setting. if you are installing from TrueNAS make sure the settings are correct. If they are not, fix and reboot the jail. If you are installing from FreeBSD...well, there are a ton of jail managers.
 - permissions. if jellyfin is installed alone into a new jail this is unlikely but worth double checking

**Comment by vongoethe** [comment]
thank you
I'll give it a try.

**Comment by vongoethe** [comment]
delete the jail and recreate, then reinstall jellyfin
everything works normal now
thank you
