### ISSUE TITLE
Jellyfin 10.8.9

### ISSUE THREAD

**Issue by septarchy** [Thefrank/jellyfin-server-freebsd#40]
Hello Frank,

Are you in the position to update to the newest version of Jellyfin?

Much appreciated! :)

**Comment by Thefrank** [comment]
https://github.com/Thefrank/jellyfin-server-freebsd/releases/tag/v10.8.9

enjoy!

**Comment by septarchy** [comment]
Glorious as ever! Thanks again Frank!
