### ISSUE TITLE
Just a user from BSD-land... Media identification

### ISSUE THREAD

**Issue by PleiadianCowboy** [Thefrank/jellyfin-server-freebsd#41]
Hi, hello, I'm just an open-Source fanboy using Ghostbsd as a Jellyfin server. Jellyfin will not complete scraping all files. When I attempt to manually go through files I get inconsistent results... For instance: Sometimes if I attempt to update a movie/tv show, the identification process works, sometime it appear to work, and sometimes it blanks out. Please ask for any logs, etc... You have dudes like me out here that truely appreciate what you do.

**Comment by Thefrank** [comment]
As @rucko24 pointed out, permissions are the common issue with that. Double check that the jellyfin user/group has write access the location you gave it for caching and database storage.
