### ISSUE TITLE
Hardware acceleration 

### ISSUE THREAD

**Issue by sevrev** [Thefrank/jellyfin-server-freebsd#46]
Hi! 

I was reading through your guide and got to [this point ](https://github.com/Thefrank/jellyfin-server-freebsd/blob/main/Installation_TrueNAS_GUI.md#hardware-encoding-intel) and then I began to wonder. Does this only enable hardware acceleration on the CPU and not GPU acceleration? I have a GTX 1660 ti that I wanted to use for acceleration but I have been really struggling with finding a way to pass the GPU through to the jail. I would not mind running jellyfin on the freebsd install directly but I'm using truenas core and it is not meant to be altered as far as I have understood. So when I came across your guide I started to wonder if it was possible. Any response is greatly appreciated. I did not know how best to reach out to you in any other way @Thefrank.

Regards
 Sevre

**Comment by Thefrank** [comment]
@sevrev "Issues" is exactly the place you can ask for help :)

I don't have any GPUs or iGPUs to test for FreeBSD but GPU acceleration SHOULD work under TrueNAS if:
- The kernel modules exist for your series of graphics card. These would be loaded for the host.
- The graphic card supports passthrough. NVIDIA is very bad about allowing passthrough on non-datacenter GPUs
- The device can be exposed to the jail (for an example, see how that is done for intel's graphics, the names might be different however)
- The drivers support everything you want them to do (https://www.nvidia.com/en-us/geforce/drivers/ -> GeForce -> GeForce 16 Series -> GeForce GTX 1660 Ti -> FreeBSD x64 -> (Your Language) -> All -> Pick a download? -> https://www.nvidia.com/en-us/drivers/results/200483/)
  - I suggest the closed source drivers here as 1) There actually appears to be manufacturer supported for FreeBSD, 2) They are actually updated, and 3) Release notes actually describe features and possible issues specific to FreeBSD

Your first step would be to see if there are kernel module drivers for your graphics card series. If there are you can continue by trying to pass the device through to the jail then finally installing the software.

I am not sure how well the drivers from NVIDIA will work INSIDE a jail as they seem designed to be installed on the host and not inside a jail (e.g., they build kernel modules)

**Comment by Thefrank** [comment]
Closing in favor of #13
