### ISSUE TITLE
Jellyfin 10.7.7 is out

### ISSUE THREAD

**Issue by nicolas-r** [Thefrank/jellyfin-server-freebsd#5]
Hi

the 10.7.7 version has been release 13 days ago.

Can you update the package please ?

Thank you

**Comment by Thefrank** [comment]
I've gone ahead a built 10.7.7 (see:https://github.com/Thefrank/jellyfin-server-freebsd/releases/tag/v10.7.7). I have not had the time to test it out fully.
close this ticket if everything works fine :)

**Comment by nicolas-r** [comment]
Hi

I just installed this version, so far so good

Thanks for the quick update
