### ISSUE TITLE
Manual HTTP traffic port change?

### ISSUE THREAD

**Issue by NathanVH8** [Thefrank/jellyfin-server-freebsd#51]
I changed the HTTP traffic port via the Dashboard from 8096 to 80 (It's on a DHCP IP address, not the TrueNAS IP), and now I can't access any part of Jellyfin. Plus the Jellyfin process is using a lot of CPU. Any suggestions on how to fix it, or should I just start over?

**Comment by Thefrank** [comment]
Can you:
Restart the service from inside jail? `service jellyfin restart`
Restart the jail from the TrueNAS GUI/console?

**Comment by Thefrank** [comment]
In that case, you might just want to manually edit the settings file and restart the service

**Comment by NathanVH8** [comment]
Could you perhaps direct me to where that file might be located? I spent several hours digging through a lot of files and didn't find the port settings.

**Comment by Thefrank** [comment]
@NathanVH8 sure!

Depending on how you set it up and configured it:
For the server:
`/var/db/jellyfin/config/` or `/HOME/USER_ACCOUNT_FOR_JELLYFIN/.config/jellyfin`
For the webclient:
`/INSTALL/PATH_OF_JELLYFIN/jellyfin-web/` (`config.json`)

**Comment by NathanVH8** [comment]
Awesome, thank you VERY much, that is the exact file I was looking for!
