### ISSUE TITLE
Enable discussions for this repository

### ISSUE THREAD

**Issue by ageekhere** [Thefrank/jellyfin-server-freebsd#53]
Hi, I really like this project! I have installed jellyfin on truenas core and have everything running. Can discussions for this repository be enabled?

**Comment by Thefrank** [comment]
I will look into that when I get some time; hopefully before the weekend

**Comment by ageekhere** [comment]
Here is the doc for enabling discussions for repository
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/enabling-or-disabling-github-discussions-for-a-repository

**Comment by ageekhere** [comment]
update?

**Comment by Thefrank** [comment]
Oh yeah! I turned them on. Thank you for the reminder!
