### ISSUE TITLE
Updating form 10.8.10 to 10.8.10_1 had issues

### ISSUE THREAD

**Issue by ageekhere** [Thefrank/jellyfin-server-freebsd#54]
So i updated from 10.8.10 to 10.8.10_1 and had a major issue. Something went wrong and jellyfin was deleted from the jail. Had to uninstall the plugin and reinstall it.

Did anyone else have an issue updating to 10.8.10_1?

**Comment by spz2k9** [comment]
Updating will only work when TrueNas Core will update the plugin to version 3... which will be in the next release of TrueNas Core (13U6).
