### ISSUE TITLE
Error installing Jellyfin on Truenas Core via Community Plugin

### ISSUE THREAD

**Issue by Nirusu99** [Thefrank/jellyfin-server-freebsd#58]
I tried to install the recommended way via the community plugin in Truenas Core `TrueNAS-13.0-U5.3`.
And it fails with the following error:
```
Error: jelly had a failure Exception: RuntimeError Message: Last 10 lines: pw: user `jellyfin' does not exist Partial plugin destroyed
```

**Comment by Thefrank** [comment]
Pinging @spz2k9 on this. Any changes on the plugin that might be breaking?

**Comment by spz2k9** [comment]
It's a change that was requested from IX... I did a temporary fix... but it will only be fixed when the next version of TrueNas Core will be released.
