### ISSUE TITLE
jellyfin start with error "Failed to create CoreCLR, HRESULT: 0x8007FF02"

### ISSUE THREAD

**Issue by GitKalle** [Thefrank/jellyfin-server-freebsd#6]
Hello,

I use the [installation instruction](https://github.com/Thefrank/jellyfin-server-freebsd/blob/main/Installation_TrueNAS_GUI.md) and tried to start the daemon but nothing happens. There are no log files from jellyfin and from the system. That's why I start jellyfin directly with:

```bash
# sudo -u jellyfin ./jellyfin --datadir /usr/local/share/jellyfinserver/data --cachedir /usr/local/share/jellyfinserver/data/.cache
```
After the command the following error appears immadiately:

`Failed to create CoreCLR, HRESULT: 0x8007FF02`

Regarding the issue jellyfin/jellyfin#5554 I never limit the memory for the jail. The output from `top` shows:

`Mem: 295M Active, 4931M Inact, 606M Laundry, 9427M Wired, 1284M Buf, 451M Free`

The owner and the group of the directory is `jellyfin`. The system is a FreeBSD 12.2 Jail.

Can somebody help?

**Comment by Thefrank** [comment]
That error occurs before anything can be logged as its a part of dotNET initialization.  

That error is usually that it can not allocate ANY memory. Make sure the jail has `allow_mlock=1` (if using `iocage`; most other jail managers should have something similar)

**Comment by GitKalle** [comment]
> `allow_mlock=1`

This helps, thanks.

I'll read the installation instruction more thoroughly next time.
