### ISSUE TITLE
Release 10.8.12 available

### ISSUE THREAD

**Issue by driesmp** [Thefrank/jellyfin-server-freebsd#63]
Hello,

Would you be able to take a look at updating the tarball to the latest release? :)
https://github.com/jellyfin/jellyfin/releases

Thank you

**Comment by Thefrank** [comment]
@driesmp Updated: https://github.com/Thefrank/jellyfin-server-freebsd/releases/tag/v10.8.12

Might not work with FreeBSD 14.0-R due to OpenSSL changes
