### ISSUE TITLE
FreeBSD and its derivatives, such as TrueNAS CORE, are NOT supported by Jellyfin

### ISSUE THREAD

**Issue by jssilva25** [Thefrank/jellyfin-server-freebsd#64]
Hello,

On v10.8.12 release notes you inform that:
`Finally, this repo no longer produces an installable pkg. You can [install ](https://www.freshports.org/multimedia/jellyfin/)jellyfin directly in FreeBSD!`

But upstream says:
`[FreeBSD](https://www.freebsd.org/) and its derivatives, such as [TrueNAS CORE](https://www.truenas.com/truenas-core/), are NOT supported by Jellyfin due to .NET officially not being compatible with these platforms.`

The fact is that TrueNAS repository has v10.8.10 since many months now and, from the previous paragraph, it seems not be upgraded soon.

I ran a number of previous releases from your work, for which I thank you; then, when the official v10.8.9 (I think) came out on TrueNAS repository, I did the upgrade with minor path adaptations, as far as I can remember, and it's been running v10.8.10_3 well since then with some minor problems.

But it is already lagging by two minor versions. So, the question is, could you please release a pkg version?

Or please tell me how I could build one myself?

Thank you.

**Comment by Thefrank** [comment]
`Jellyfin` and its developers do not officially support FreeBSD as FreeBSD is not an official dotNET platform. It is a "community supported" platform. You can read it as "Our product MIGHT work but we can not help you if you run into issues". This is why I also ask that people do not bring FreeBSD issues into the Jellyfin forums but instead open an issue here instead.

I no longer produce a pkg for this as there is an actual port maintainer for it. I have notified the maintainer of the update.

If you want to generate your own package, you can use the ports system for that. Bumping the version in the `Makefile` should be enough

**Comment by jssilva25** [comment]
Thank you for your reply and work.

**Comment by michaelburton** [comment]
Just bumping the version in the makefile isn't enough. You also need to update `distinfo` with the sha256 and size of the new version, like this:

```
SHA256 (jellyfin-combined_10.8.13_freebsd-amd64.tar.gz) = 17ffd823b6df5fbb6ad32988377962d8a4985e230d1b4a8e71fcbcf19e12473e
SIZE (jellyfin-combined_10.8.13_freebsd-amd64.tar.gz) = 70441475
```

Even after that, `make install` fails because it can't find some files it's expecting. Hopefully the port is updated soon for the security fixes.

**Comment by Thefrank** [comment]
"Bump version" was a bit too much shorthand. Sorry about that.
`make makesum` will regenerate the `distinfo`
`make makeplist` will output the updated `pkg-plist`
Those should be enough for `make install` to work`

**Comment by mvanbaak** [comment]
I try to update the `multimedia/jellyfin` port as soon as I get a ping from Thefrank about a new version.
Also, Thefrank is working on creating a port version that can be built from source. if that is in, I can follow the tags on the upstream jellyfin project.

As mentioned before, this is community work, not supported officially by neither Jellyfin nor FreeBSD

**Comment by Thefrank** [comment]
Yep! An experimental ports build can be found here: https://github.com/Thefrank/jellyfin-server-freebsd/tree/main/building/ports/jellyfin for those feeling adventurous :)

**Comment by rucko24** [comment]
> Hello,
> 
> On v10.8.12 release notes you inform that: `Finally, this repo no longer produces an installable pkg. You can [install ](https://www.freshports.org/multimedia/jellyfin/)jellyfin directly in FreeBSD!`
> 
> But upstream says: `[FreeBSD](https://www.freebsd.org/) and its derivatives, such as [TrueNAS CORE](https://www.truenas.com/truenas-core/), are NOT supported by Jellyfin due to .NET officially not being compatible with these platforms.`
> 
> The fact is that TrueNAS repository has v10.8.10 since many months now and, from the previous paragraph, it seems not be upgraded soon.
> 
> I ran a number of previous releases from your work, for which I thank you; then, when the official v10.8.9 (I think) came out on TrueNAS repository, I did the upgrade with minor path adaptations, as far as I can remember, and it's been running v10.8.10_3 well since then with some minor problems.
> 
> But it is already lagging by two minor versions. So, the question is, could you please release a pkg version?
> 
> Or please tell me how I could build one myself?
> 
> Thank you.

---

How are you doing ? 

I have never had any problems but using XigmaNAS **13.2.0.5 - Heighliner (revision 9884)**, being even less problematic and more permissive with the configuration of the jails.

Even right now I have Thegrank version 10.9.4

![image](https://github.com/Thefrank/jellyfin-server-freebsd/assets/17187599/c774ebfd-22f9-4fb5-985b-dface8ce0cb5)
