### ISSUE TITLE
Issues with name resolution inside jellyfin

### ISSUE THREAD

**Issue by turin331** [Thefrank/jellyfin-server-freebsd#66]
Out of no where jellyfin suddenly fails to resolve hostnames for the various services. For example these are the errors when the plugin catalog is attempted to be loaded: 
```

[2023-12-26 22:49:40.330 +01:00] [ERR] [41] Emby.Server.Implementations.Updates.InstallationManager: An error occurred while accessing the plugin manifest: "https://repo.jellyfin.org/releases/plugin/manifest-stable.json"
System.Net.Http.HttpRequestException: Name does not resolve (repo.jellyfin.org:443)
```

The same thing happens when trying to access any metadata website or api. 
It is the manually created jails (not the community plugin). Everything is on the latest version. 

Went through the troubleshooting segment about jellyfin "not being able to use the internet" and everything is as they should be. 
Not entirely sure about part about disabling file monitoring (not sure which setting is this) but i supposed that should not be related to name resolution. 

Resolution works fine from the jail shell. Anyone has any ideas?

**Comment by Thefrank** [comment]
Does restarting the jail solve issue? Does the issue return some point after restarting jail? If the answer is "yes" to both, then try turning off file monitoring in jellyfin and see if that resolves the issue.

**Comment by turin331** [comment]
> Does restarting the jail solve issue? Does the issue return some point after restarting jail? If the answer is "yes" to both, then try turning off file monitoring in jellyfin and see if that resolves the issue.

The issue is not resolved after restating the jail and even the whole system. 

That being how to disable is the file monitoring? Disabled the automatic scans?

**Comment by Thefrank** [comment]
> That being said how to disable the file monitoring? Disable the automatic scans?

From your profile menu select "Dashboard" under "Administration". Click Libraries. On each library click the triple dot and select "Manage Library". Unselect "Enable real time monitoring". Click OK

If rebooting the machine did not fix the issue then something else is going on with Jellyfin or you have 100k+ files for it to monitor and Jellyfin immediately has problems when the machine reboots.

Does `ping one.one.one.one` work from inside the jail?
Does `curl -l https://repo.jellyfin.org/` work? Does it return an HTML response? 

Are you sure your router/firewall is not blocking Jellyfin?

**Comment by turin331** [comment]
Reboot does not fix the issue but at random times the resolution does work. I should sth close to 50k flies since i have added music recently so maybe this is the monitoring issue. 

ping and curl from the jail works and the router/firewall is not blocking it. 

Will disable the monitoring and see what happens. Thank you!

**Comment by turin331** [comment]
ok have been testing it for the last couple of weeks. It seem that is indeed the issue. Weird it did not trigger before as i have not added anything big recently and was fine for so long. Thank you!
