### ISSUE TITLE
how can i pass env variables? 

### ISSUE THREAD

**Issue by biGdada** [Thefrank/jellyfin-server-freebsd#7]
hi. im trying to pass 2 variables, namely JELLYFIN_FFmpeg__analyzeduration and JELLYFIN_FFmpeg__probesize.

both are ignored.
output of ps axeww | grep JELLYFIN

`72019  8  IJ   0:33.34 LANG=en_US.UTF-8 PATH=/sbin:/bin:/usr/sbin:/usr/bin JELLYFIN_FFmpeg__probesize=8G PWD=/ TERM=xterm-256color HOME=/ JELLYFIN_FFmpeg__analyzeduration=5000M LC_ALL=en_US.UTF-8 RC_PID=71636 /jellyfin/jellyfin/jellyfin --service -d /jellyfin/data -C /jellyfin/cache -c /jellyfin/config -l /jellyfin/log --ffmpeg /usr/local/bin/ffmpeg`

**Comment by Thefrank** [comment]
The easiest way would be to add `${name}_env` in the rc file to pass environment variables to it. I am more of a fan of using `${name}_env_file` and using a file for that alternatively adding `/usr/local/rc.conf,d/<SERVICE>` should perform the same action without the need to mess with the RC file

For a more detailed break down: https://www.freebsd.org/cgi/man.cgi?query=rc.subr&sektion=8&n=1

**Comment by biGdada** [comment]
the thing is - it doesnt work even  from command line.

**Comment by Thefrank** [comment]
From your original post it does actually look like those are being passed in. What errors is jellyfin returning to indicate its not taking those env vars?

**Comment by biGdada** [comment]
`[mpegts @ 0x806e05000] Could not find codec parameters for stream 0 (Video: h264 ([27][0][0][0] / 0x001B), none): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options`

JELLYFIN_FFmpeg__analyzeduration and JELLYFIN_FFmpeg__probesize are being ignored.

**Comment by Thefrank** [comment]
what do debug/trace logs show that jellyfin passes to ffmpeg?

does ffmpeg/ffprobe accept the `analyzeduration` and `probesize` parameters correctly? if yes, what does it return for the video you are scanning if run from outside of jellyfin?

**Comment by biGdada** [comment]
according to the same log this is the command being run by jellyfin:
`
/usr/local/bin/ffmpeg -analyzeduration 3000000 -user_agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.85 Safari/537.36" -fflags +igndts -f mpegts -i "http://[censored]:6878/ace/getstream?id=54dba5e0ffc80aa60d2f4a9b8f751f2d9b95e9cd&.mp4" -map_metadata -1 -map_chapters -1 -threads 0 -sn -codec:v:0 libx264 -pix_fmt yuv420p -preset superfast -crf 23 -maxrate 35937032 -bufsize 71874064 -profile:v:0 high -level 41 -x264opts:0 subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none  -force_key_frames:0 "expr:gte(t,n_forced*3)" -start_at_zero -flags -global_header -vsync cfr -codec:a:0 aac -ac 6 -ab 192000 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_base_url "hls/16921906273e8b454ca13a521a2d17af/" -hls_playlist_type event -hls_segment_filename "/jellyfin/data/transcodes/16921906273e8b454ca13a521a2d17af%d.ts" -y "/jellyfin/data/transcodes/16921906273e8b454ca13a521a2d17af.m3u8"
`

notice the "-analyzeduration 3000000". no matter what i am setting "JELLYFIN_FFmpeg__analyzeduration" to, the command is the same.

**Comment by Thefrank** [comment]
I will have to look into the code a bit to figure out where Jellyfin handles env vars. Passing vars via CLI should be fine, but clearly its handling it differently
I am also confused as to why `Could not find codec parameters for stream 0` is ending up being fatal. It is a warning not an error, so it should not be halting Jellyfin from doing anything.

**Comment by biGdada** [comment]
its not fatal per se, it means that jellyfin cannot decode the stream - so no video.

**Comment by Thefrank** [comment]
Well, I still can't figure out why Jellyfin is not honoring those env vars but it looks like it is overriding some of the defaults and it shouldn't be.

 `analyzeduration` should be `5000000` by default as it only takes an integer in microseconds and `probesize` which has the same default but as integer in bytes. I have no idea how it converts things like `8G` and `5000M` internally.

1. Does `ffprobe` correctly read the file (a.k.a. does it match how you encoded the file when you first made it)? Something like MediaInfo in Windows/Linux will work just as well.
2. Does the file play correctly on another desktop platform? (e.g., Windows, OSX, Linux)
3. Does the file play correctly on other apps on FreeBSD? (e.g., Plex or Kodi). Both Plex and Kodi use custom ffmpeg for transcoding and playback whereas Jellyfin uses the ffmpeg that it either finds on PATH or is directly pointed to via parameter.

**Comment by biGdada** [comment]
1. it's not a file, it's a stream generated from acestream. thus cant use mediainfo 
2. it does. plays without problem in vlc on MacOS/ linux. 
3. not sure how this is relevant? anyway, the stream plays on FreeBSD in VLC. AFAIK there is no FreeBSD version of Kodi....

**Comment by Thefrank** [comment]
I think I see what is going on now

https://github.com/jellyfin/jellyfin/blob/master/Emby.Server.Implementations/ConfigurationOptions.cs defines the defaults for the two items you are trying to override. That should be fine however...
https://github.com/jellyfin/jellyfin/blob/45ceba7ad152de85956af51272c53c29cbbd5a70/Emby.Server.Implementations/Library/LiveStreamHelper.cs#L67-L77 seems to create is own delay and analyze duration for livestreams.

I don't see a way to override that but that might not be the root issue. It could verywell be an issue with how ffmpeg is built under FreeBSD and its handling of HLS Streams. The fact that the stream plays well under VLC makes me lean more towards ffmpeg and/or jellyfin hardcoded settings.

I would open a ticket upstream and see if you can get anymore help with this.
I am going to leave this ticket open [unless you want to close it] for the time being incase anyone else is running into this issue

**Comment by Thefrank** [comment]
Stale + newer versions of jellyfin should give more generous defaults.

Feel free to reopen or make a new issue
