### ISSUE TITLE
Correct way to update the Jellyfin plugin?

### ISSUE THREAD

**Issue by ageekhere** [Thefrank/jellyfin-server-freebsd#70]
Do i first stop the jail, click update then start?
![Screenshot 2024-04-06 180245](https://github.com/Thefrank/jellyfin-server-freebsd/assets/13173133/dc898464-3052-4fc6-abdb-0b3280ab9946)

Does the jellyfin config get reset on updates?

**Comment by Thefrank** [comment]
Yes and Yes. If you want to keep your config/cache/data safe I suggest using a dataset and mounting that in.

**Comment by ageekhere** [comment]
> Yes and Yes. If you want to keep your config/cache/data safe I suggest using a dataset and mounting that in.

I have created a data set for jellyfin and changed the path for
cache path
metadata path
transcode path

Are there any more paths that i can change to save into the data set?

**Comment by Thefrank** [comment]
Depending on your usage, you might not need to save the transcodes.
You will want to keep the "datadir" which defaults to `/var/db/jellyfin`
