### ISSUE TITLE
Doesnt Scan Libraries Efficiently

### ISSUE THREAD

**Issue by bornlibra23** [Thefrank/jellyfin-server-freebsd#72]
I have installed both jellyfin & plex on TrueNAS 13.2-RELEASE-p11 in jails.

Plex took 5 minutes to scan over 2 TB of media including artwork etc.
Jellyfin has been running for over 5 days without completing the scan or downloading artworks.

I dont think I have misconfigured it somehow. Still any ideas? This didnt happen on my last windows based Jellyfin

[2024-05-10 17:33:12.218 +05:30] [ERR] [57] MediaBrowser.Providers.Movies.MovieMetadataService: Error in "TheMovieDb"
System.Net.Http.HttpRequestException: Operation timed out (api.themoviedb.org:443)
 ---> System.Net.Sockets.SocketException (60): Operation timed out
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)

![image](https://github.com/Thefrank/jellyfin-server-freebsd/assets/1274358/b8ef8409-c23f-456a-8cc6-0a0dcfb925b4)
![image](https://github.com/Thefrank/jellyfin-server-freebsd/assets/1274358/3fee9040-c7cb-4438-a4f0-960caa19ba97)
![image](https://github.com/Thefrank/jellyfin-server-freebsd/assets/1274358/1ac7bed4-37e7-4202-a21d-da40f69372a7)
![image](https://github.com/Thefrank/jellyfin-server-freebsd/assets/1274358/32490f04-0e06-4c07-8f09-159f6194ca18)

**Comment by Thefrank** [comment]
@bornlibra23 Out of curiosity, what ended up as the solution?

**Comment by bornlibra23** [comment]
Hi Frank.

Thanks for reaching out. I appreciate it.

There is no solution currently. I even tried switching to "The Open Movie
Database" as the primary metadata scraper for everything. But no luck. It
doesn't generate any logs. Also deducing from the UI options Jellyfin
always uses TMDB for season & episode scraping. So I am screwed there.

Currently I am dead in the water.

I closed the ticket as it seems that it's a jellyfin issue & not with your
version.

The situation sucks. I am going to try jellyfin on a Windows or Linux
system & have Samba export from the NAS. It's a very sad situation.

**Comment by Thefrank** [comment]
Using a sample of 500GB of data
On a new install of Jellyfin on FreeBSD

it does appear slower than Windows (data mounted via SMB) or Linux (data mounted via VM mount). 

It looks like it comes from ffmpeg being much slower to generate things like screenshots, thumbnails, and chapter scrub shots. I did not see any difference in gathering metadata between the platforms. The difference is so large that the task has not finished on FreeBSD yet but already has finished on the Windows and Linux VMs INSIDE the same machine running the FreeBSD version natively!

Plex on FreeBSD uses its own fork of FFmpeg built with their own fork of Clang/LLVM.

**Comment by bornlibra23** [comment]
Yes that may be the root cause of the problem.
But I am not worried about the  screenshots, thumbnails, and chapter scrub
shots etc so this shouldnt impact me at all. I would disable them if I
could.
I just need the posters & metadata to be downloaded. Its taking ages &
failing at that as well. Plex did all this in 5 minutes.

Is there a way I can disable the first & achieve the second?
