### ISSUE TITLE
Update to version 10.9.0

### ISSUE THREAD

**Issue by matizul** [Thefrank/jellyfin-server-freebsd#74]
Hey, can you please update it to version 10.9.0

**Comment by Thefrank** [comment]
https://github.com/Thefrank/jellyfin-server-freebsd/releases/tag/v10.9.2 ?

**Comment by matizul** [comment]
Oh, I’m blind, so sorry!

**Comment by Thefrank** [comment]
No problem! 
The port version should be updated in the next few days and should be on the port mirrors (aka you can `pkg install jellyfin`) in about a week.
