### ISSUE TITLE
Error after updating jellyfin not repsonding

### ISSUE THREAD

**Issue by Arty03** [Thefrank/jellyfin-server-freebsd#77]
Jun  7 00:05:53 JellyFin dhclient[96833]: receive_packet failed on epair0b: Device not configured
Jun  7 00:05:53 JellyFin dhclient[96833]: ioctl(SIOCGIFFLAGS) on epair0b: Operation not permitted
Jun  7 00:05:53 JellyFin dhclient[96833]: Interface epair0b no longer appears valid.
Jun  7 00:05:53 JellyFin dhclient[96833]: No live interfaces to poll on - exiting.
Jun  7 00:05:53 JellyFin dhclient[96833]: exiting.
Jun  7 00:05:53 JellyFin dhclient[96833]: connection closed
Jun  7 00:05:53 JellyFin  dhclient[96833]: exiting.

this was after updating jelly fin to the latest of this site , i was running the prior build.
re installing same result , manually installing shell commands same result

Running TrueNAS-13.0-STABLE
jail: 13.2-RELEASE-p11

**Comment by Thefrank** [comment]
Running a newer version of a jail (FreeBSD 13.2) on an older host (TrueNAS 13.0 / FreeBSD 13.1) can have unexpected / unknown behavior. 

You can find some workarounds here #75 or you can wait until TrueNAS updates to a FreeBSD based on 13.3+.

**Comment by Arty03** [comment]
> Running a newer version of a jail (FreeBSD 13.2) on an older host (TrueNAS 13.0 / FreeBSD 13.1) can have unexpected / unknown behavior.
> 
> You can find some workarounds here #75 or you can wait until TrueNAS updates to a FreeBSD based on 13.3+.

sooo wait then

im not that tech savy so waht is the work around to boot jelly fin  downgrading?

**Comment by Arty03** [comment]
> Good to hear the beta train and jellyfin are working for you! There should be a stable release of TrueNAS Core 13.3 some time this month

Is there a way to transfer the config to another jail ?

**Comment by Thefrank** [comment]
If you use a custom ruleset and want hardware acceleration you will need to either add those parameters to your custom ruleset or make another one that includes both your custom ruleset and the parameters to enable hardware acceleration
