### ISSUE TITLE
After the upgrade to 10.7.7, jellyfin-web still 10.7.6

### ISSUE THREAD

**Issue by nicolas-r** [Thefrank/jellyfin-server-freebsd#8]
Hi

After I upgrade to 10.7.7, the server reports 10.7.7 as version but i still get 10.7.6 as version for jellyfin-web instead of 10.7.7 in the active devices

example
Edge Chromium
Jellyfin Web 10.7.6

Firefox
Jellyfin Web 10.7.6

I do some grep and found that

root@j-jellyfin:/usr/local/share/jellyfinserver/jellyfin-web # grep -rc "10\.7\.7" * | grep -v ":0"
root@j-jellyfin:/usr/local/share/jellyfinserver/jellyfin-web # grep -rc "10\.7\.6" * | grep -v ":0"
main.0f183787a2f78055e856.bundle.js:1
root@j-jellyfin:/usr/local/share/jellyfinserver/jellyfin-web #

Is this normal for you ?

Thanks

Nicolas

**Comment by Thefrank** [comment]
hrm... it SHOULD be the correct version even if I forgot to manually bump the version number.
That being said, just make sure (and avoid future issues) I will rebuild/republish both the Jellyfin-Web and installer package.
I should have some time in the next day or so to do that. I will give you a ping when its done :)

Thanks for letting me know!

**Comment by Thefrank** [comment]
```sh
root@radport:/usr/ports/multimedia/jellyfinserver/work/jf/jellyfin-web # grep -rc "10.7.7" * | grep -v ":0"
main.0f183787a2f78055e856.bundle.js:1
root@radport:/usr/ports/multimedia/jellyfinserver/work/jf/jellyfin-web # grep -rc "10.7.6" * | grep -v ":0"
libraries/subtitles-octopus-worker-legacy.js:1
main.0f183787a2f78055e856.bundle.js:1
```

@nicolas-r I updated (and uploaded): `jellyfin-web`, `jellyfin-combined`, and `jellyfinserver-10.7.7.pkg`

Let me know if you have any other issues, if not, feel free to close the issue :)

**Comment by nicolas-r** [comment]
Hi

I have installed the package found in release but still 10.7..6

I have downloaded https://github.com/Thefrank/jellyfin-server-freebsd/releases/download/v10.7.7/jellyfinserver-10.7.7.pkg, extract the data into /tmp and still have 10.7.6

root@shadowland[...cal/share/jellyfinserver/jellyfin-web]# pwd
/tmp/usr/local/share/jellyfinserver/jellyfin-web
root@shadowland[...cal/share/jellyfinserver/jellyfin-web]# grep -rc "10\.7\.7" * | grep -v ":0"
root@shadowland[...cal/share/jellyfinserver/jellyfin-web]# grep -rc "10\.7\.6" * | grep -v ":0"
main.0f183787a2f78055e856.bundle.js:1

Maybe you should add a release number like jellyfinserver-10.7.7-1.pkg to be sure we are using the correct package

I also downoad https://github.com/Thefrank/jellyfin-server-freebsd/releases/download/v10.7.7/jellyfin-web_10.7.7_portable.tar.gz and see the 10.7.6

Maybe there was an issue with the upload ? Or I do something wrong

Nicolas

**Comment by Thefrank** [comment]
I am not quite sure what is going on there. I can not reproduce it :(
```sh
root@building:/tmp # fetch https://github.com/Thefrank/jellyfin-server-freebsd/releases/download/v10.7.7/jellyfinserver-10.7.7.pkg
jellyfinserver-10.7.7.pkg                               53 MB   52 MBps    01s
root@building:/tmp # tar xf jellyfinserver-10.7.7.pkg 
tar: Removing leading '/' from member names  
root@building:/tmp # cd usr/local/share/jellyfinserver/jellyfin-web/
root@building:/tmp/usr/local/share/jellyfinserver/jellyfin-web # grep -rc "10.7.7" * | grep -v ":0"
main.0f183787a2f78055e856.bundle.js:1
root@building:/tmp/usr/local/share/jellyfinserver/jellyfin-web # grep -rc "10.7.6" * | grep -v ":0"
libraries/subtitles-octopus-worker-legacy.js:1
main.0f183787a2f78055e856.bundle.js:1
```

**Comment by nicolas-r** [comment]
We have to use backslash in the grep command, otherwise grep will interpret the dot as any character

root@j-jellyfin:/usr/local/share/jellyfinserver/jellyfin-web # grep -rc "10\.7\.6" * | grep -v ":0"
main.0f183787a2f78055e856.bundle.js:1

root@j-jellyfin:/usr/local/share/jellyfinserver/jellyfin-web # grep -rc "10\.7\.7" * | grep -v ":0"

To be sure this is not expected, I have downloaded the sources, extract them and found that in src/components/apphost.js

import appSettings from '../scripts/settings/appSettings';
import browser from '../scripts/browser';
import { Events } from 'jellyfin-apiclient';
import * as htmlMediaHelper from '../components/htmlMediaHelper';
import * as webSettings from '../scripts/settings/webSettings';
import globalize from '../scripts/globalize';
import profileBuilder from '../scripts/browserDeviceProfile';

const appName = 'Jellyfin Web';
const appVersion = '10.7.6';

I'll try to build it inside Linux VM and chehck the result

**Comment by Thefrank** [comment]
if you want to paste code you use the "code block" feature in github. I checked my build environment:
```sh
root@building:~/jellyfin-web # git branch
* (HEAD detached at v10.7.7)
  master
  release-10.7.z
root@building:~/jellyfin-web # git grep "10\.7\.7"
build.yaml:version: "10.7.7"
debian/changelog:jellyfin-web (10.7.7-1) unstable; urgency=medium
debian/changelog:  * New upstream version 10.7.7; release changelog at https://github.com/jellyfin/jellyfin-web/releases/tag/v10.7.7
fedora/jellyfin-web.spec:Version:        10.7.7
fedora/jellyfin-web.spec:- New upstream version 10.7.7; release changelog at https://github.com/jellyfin/jellyfin-web/releases/tag/v10.7.7
root@building:~/jellyfin-web # git status
HEAD detached at v10.7.7
nothing to commit, working tree clean
root@building:~/jellyfin-web # git log
commit be195b0e240b4a4b871eb6a7fe8e4830bd9ab12c (HEAD, tag: v10.7.7, origin/release-10.7.z)
Author: Joshua M. Boniface <joshua@boniface.me>
Date:   Sun Sep 5 22:33:01 2021 -0400

    Bump version to 10.7.7

```

**Comment by nicolas-r** [comment]
Sorry for the wrong copy/paste

I should have check the issue on their side in fact.

https://github.com/jellyfin/jellyfin-web/issues/2973

Sorry for the noise and thanks for your work again

Nicolas
