### ISSUE TITLE
dotnet 8

### ISSUE THREAD

**Issue by m-ghaoui** [Thefrank/jellyfin-server-freebsd#80]
dotnet 8 has been ported to FreeBSD thanks to a lot of hard work by its maintainer:

https://www.freshports.org/lang/dotnet/

Any plans to remove the binaries from this project and use dotnet instead?

**Comment by mvanbaak** [comment]
Work on this is ongoing. Nothing final yet

**Comment by Thefrank** [comment]
https://github.com/Thefrank/jellyfin-server-freebsd/blob/main/README.md#upcoming-changes-to-this-repo
