### ISSUE TITLE
How to install the binaries here

### ISSUE THREAD

**Issue by jssilva25** [Thefrank/jellyfin-server-freebsd#82]
It certainly is a naive question.

I upgraded TrueNas Core from v13.0-U6 to v13.3 this morning using a downloaded manual file because the WebGUI still doesn't show this train. Actually, it only shows Scale Trains as of this writing. 

Then I upgraded the jail that was running Jellyfin v10.8.13, with v13.2p12 (shouldn't have upgraded from 13.0 but it was working, kind of...) to v13.3, using the shell. The result was the upgrade removing the Jellyfin package, I can understand why, because the 13.3 repo doesn't have this pkg.

After reading a lot, since early morning, I rolled back the jail, just to be safe, and created a new jail with 13.3, with the intention of importing all the settings later..

Now comes the Jellyfin installation. @Thefrank teaches us to use the port system but, frankly, it takes too long, at least on my system. Furthermore, the port system version is now at 10.9.6 whereas here is at 10.9.9. The pkg is not available anywhere.

So, finally, **how can I use the binaries here for 10.9.9 to install into a jail?** Thank you.

**Comment by jssilva25** [comment]
@rucko24 Your "eyes" were actually very helpful, thank you, no sarcasm meant :) , it stimulated my mind and helped me find my way through.

Although I don't know exactly what you meant, I interpreted it as "If you look and see nothing, look again".

So, I was able to install 10.9.6 with pkg. I hope to be able to catch-up soon to 10.9.9.

Thank you, closed.

**Comment by Thefrank** [comment]
[These commands assume you are root inside the jail you want to modify. If you want to use a jail manager instead just modify the commands to use the jail manager (e.g., `sudo cbsd jexec jname=JELLYFINJAIL "COMMAND"`)]

Make sure to stop the service before changing anything. 

If you have the pkg version installed (currently 10.9.6) and have a current jail (either 13.3 or 14.1) you can, **but I advise you to wait until the port is updated**, just overwrite the old binaries with the newer ones. Or, as the default behavior of the `jellyfin` port is to store things in `/var/db/` and `/var/cache` if you are sure that you don't store anything important in the `jellyfin` binaries path then you can also just delete the binaries path and make a new one with binaries here (`tar xf JELLYFINVERSION.tar.gz -C /JELLYFIN/BINARIES/LOCATION`)

Make sure the ownership is correct (`chown -R JELLYFINUID:JELLYFINGID /JELLYFIN/BINARIES/LOCATION`)

Restart the service.

**Comment by jssilva25** [comment]
@Thefrank I closed the issue just before your helpful comment popped up, sorry.

I'll study it now and I'm sure it'll help me to install 10.9.9.

Thank you again.

**Comment by rucko24** [comment]
> @rucko24 Your "eyes" were actually very helpful, thank you, no sarcasm meant :) , it stimulated my mind and helped me find my way through.
> 
> Although I don't know exactly what you meant, I interpreted it as "If you look and see nothing, look again".
> 
> So, I was able to install 10.9.6 with pkg. I hope to be able to catch-up soon to 10.9.9.
> 
> Thank you, closed.

Homie, i need this too, i only read for the informatio n

**Comment by jssilva25** [comment]
@Thefrank Thank you, so simple that I didn't consider the possibility, but you must have a previous compatible place holder, though.

Anyway, I renamed the folder jellyfin to .old, made a new one and decompressed all the files there. By the way, the permissions on the 10.9.6 folder are root:wheel. Also, the old folder has some files more.

But it didn't work and sincerely, after two minutes, I reverted the whole thing and it's working with 10.9.6 which is good enough for me. I guess I'll just wait for 10.9.9 to reach the "latest" repo.

Thank you for your extended help.

**Comment by jssilva25** [comment]
@rucko24 Let's hope I'm not forgetting anything, it's been a full hard day on this. 

First you have to upgrade TrueNas Core to 13.3. The dashboard GUI still hasn't got the right Train; actually it has none, as of this writing.

So, get the 13.3 file from here: https://download-core.sys.truenas.net/13.3/STABLE/RELEASE/TrueNAS-13.3-RELEASE-manual-update.tar

Then stop all your jails, VM's and non essential services and use your GUI dashboard to install the manual update file that you dowloaded above.

This following procedure also applies to the other jails, not plugins, but let's focus on the Jellyfin jail.

The Jellyfin jail should be stopped. Open a shell on TrueNas and do:
```
iocage fetch
[0] 13.3-RELEASE
[1] 14.0-RELEASE
[2] 14.1-RELEASE
```

Chose the 13.3 to fetch it to the system. This is essential for the next upgrades.

The next is the tricky part that fooled me. You must tell your jail that we want to use the "latest" repo. Otherwise, during the jail upgrade process, it will uninstall jellyfin because there isn't such a package on the normal repo. Only the "latest" repo has the 10.9.6 package.

So, tell the jail you want, the "latest" repo; still on TrueNas shell do:
```
mkdir -p /usr/local/etc/pkg/repos
echo 'FreeBSD: { url: "pkg+http://pkg.FreeBSD.org/${ABI}/latest" }' > /usr/local/etc/pkg/repos/FreeBSD.conf
```
Now you can safely perform the upgrade, still on TreuNas shell:
`iocage upgrade -r 13.3-RELEASE jellyfin-server # or whatever your jail name is`
Accept all the defaults

After a successful upgrade, start your jail and enter it with a shell (or you can also do this from the TrueNas shell with iocage exec commands):
```
jls # for checking the jail number
jexec n csh # where "n" is the jail number
```
Now you are inside the jail, do:
```
pkg update -f # to ensure using "latest" repo
pkg search jellyfin # check that 10.9.6 is available
pkg upgrade
exit
```
Now you are again on a TrueNas shell, restart the jail:
`iocage restart jellyfin-server # or whatever the name is`

Test jellyfin_ip:8096 and check it is upgraded to 10.9.6

That's it, I hope I got everything right, that's my humble give-back.

Keep well.

**Comment by rucko24** [comment]
> @rucko24 Let's hope I'm not forgetting anything, it's been a full hard day on this.
> 
> First you have to upgrade TrueNas Core to 13.3. The dashboard GUI still hasn't got the right Train; actually it has none, as of this writing.
> 
> So, get the 13.3 file from here: https://download-core.sys.truenas.net/13.3/STABLE/RELEASE/TrueNAS-13.3-RELEASE-manual-update.tar
> 
> Then stop all your jails, VM's and non essential services and use your GUI dashboard to install the manual update file that you dowloaded above.
> 
> This following procedure also applies to the other jails, not plugins, but let's focus on the Jellyfin jail.
> 
> The Jellyfin jail should be stopped. Open a shell on TrueNas and do:
> 
> ```
> iocage fetch
> [0] 13.3-RELEASE
> [1] 14.0-RELEASE
> [2] 14.1-RELEASE
> ```
> 
> Chose the 13.3 to fetch it to the system. This is essential for the next upgrades.
> 
> The next is the tricky part that fooled me. You must tell your jail that we want to use the "latest" repo. Otherwise, during the jail upgrade process, it will uninstall jellyfin because there isn't such a package on the normal repo. Only the "latest" repo has the 10.9.6 package.
> 
> So, tell the jail you want, the "latest" repo; still on TrueNas shell do:
> 
> ```
> mkdir -p /usr/local/etc/pkg/repos
> echo 'FreeBSD: { url: "pkg+http://pkg.FreeBSD.org/${ABI}/latest" }' > /usr/local/etc/pkg/repos/FreeBSD.conf
> ```
> 
> Now you can safely perform the upgrade, still on TreuNas shell: `iocage upgrade -r 13.3-RELEASE jellyfin-server # or whatever your jail name is` Accept all the defaults
> 
> After a successful upgrade, start your jail and enter it with a shell (or you can also do this from the TrueNas shell with iocage exec commands):
> 
> ```
> jls # for checking the jail number
> jexec n csh # where "n" is the jail number
> ```
> 
> Now you are inside the jail, do:
> 
> ```
> pkg update -f # to ensure using "latest" repo
> pkg search jellyfin # check that 10.9.6 is available
> pkg upgrade
> exit
> ```
> 
> Now you are again on a TrueNas shell, restart the jail: `iocage restart jellyfin-server # or whatever the name is`
> 
> Test jellyfin_ip:8096 and check it is upgraded to 10.9.6
> 
> That's it, I hope I got everything right, that's my humble give-back.
> 
> Keep well.

Nice job homie, but i'm using XigmaNAS, but thank you for your steps
