### ISSUE TITLE
Not able to update sucessfully.

### ISSUE THREAD

**Issue by nx6** [Thefrank/jellyfin-server-freebsd#83]
I've updated my TrueNAS to 13.3 and am now trying to update jellyfin. I currently have 10.8.13 running on a 13.2 jail, installed from pkg. I don't use hardware acceleration, but I do have the base URL changed to facilitate using a reverse proxy.

I stop the service, run `pkg update && pkg upgrade` and when things are all installed start the service again (have also tried stopping the entire jail and restarting it) and it comes out the same: The web interface cannot be reached on the local IP. Clients are not seeing the server running, but the jellyfin process is running on the jail. Trying to figure out what I'm doing wrong because this has been an issue for me for some time. I have been playing around with jellyfin for a year or two now. I was using the TrueNAS community plugin before and I had the same issue whenever I tried to install an update to the Plugin: The server wouldn't be accessible afterwards. I figured changing to a plain jail setup would make that less likely. I usually end up trashing things and starting over again with a fresh install but would like to avoid redoing libraries.

**Comment by Thefrank** [comment]
Try and use a 13.3 jail or upgrade your current one with your jail manager. You should be able to do this from the TrueNAS console: `iocage upgrade -r 13.3-RELEASE NAMEOFJAIL`. You may have to respond to some problems usually `y` if there is a y/n or `q` if it is just listing files without a prompt. You should restart the jail after doing this just to make sure everything got upgraded. 

This should resolve it. If not, I might need some more details about what is occurring in the jail but I can get those later.

[Rant]
Finally, `pkg update` or `upgrade` should have given a warning about a kernel version mismatch when trying to install packages from a newer (13.3) repo than what your jail is (13.2). TBH most people ignore warnings and this really should be a halting error. I don't blame you for either ignoring this or simply skipping over it. This comes pretty close to the linux `Yes, do as I say!` level of bad messaging.
[/Rant]

**Comment by nx6** [comment]
Wow. That actually worked! Jail updated and upgrade to 10.9.6 is running/reachable. Thanks.
Makes me wonder if some of the previous times I failed at updating it was really just a jail issue.
