### ISSUE TITLE
Unable to connect after installing truenas core plugin (10.9.6)

### ISSUE THREAD

**Issue by MoritzSchrenk** [Thefrank/jellyfin-server-freebsd#85]
Hi,

I did a clean installation from the plugin. Everything seemed to be fine, but it is not responding on the local network.

`service jellyfin status`
returns
`jellyfin is running as pid xxxxx`

`ps aux`
shows jellyfin running with the same pid from the following command:
`daemon: /usr/local`

I don't fully understand `netstat`, but it doesn't appear to be showing anything jellyfin related:
![image](https://github.com/user-attachments/assets/10a438d4-f1b5-4d90-8dca-b3cb43d33262)

`sockstat ` does not show jellyfin

So to me it seems like jellyfin is running but not listening on the port?

freebsd version is 13.2-RELEASE-p12
TrueNAS core version is TrueNAS-13.3-RELEASE

**Comment by Thefrank** [comment]
The daemon is running but not the actual `jellyfin` program. There should be two entries that `ps aux` returns for "`jellyfin`"

Make sure `allow.mlock=1` is set. `jellyfin` needs this to work correctly.
Double check that permissions are correct.
This should not be an issue but you might want to update the jail to FreeBSD 13.3

**Comment by MoritzSchrenk** [comment]
Did not manage to upgrade the jail for some reason, but I created a new 13.3 jail and followed the manual steps instead of the plugin, and it seems to be working now.
