### ISSUE TITLE
Does this work without VNET?

### ISSUE THREAD

**Issue by lifepillar** [Thefrank/jellyfin-server-freebsd#9]
Is VNET a hard requirement to run this package in a jail? Or is it enough to enable raw sockets?

**Comment by Thefrank** [comment]
Yes, **but** you are welcome to give it a shot without `VNET`. I had networking issues with dotNET running in jails without `VNET` however it has been more than a year since I revisited it.

If everything works fine for you, let me know, and I will drop the requirement in the guide

**Comment by lifepillar** [comment]
It appears to be functional in a standard jail, except for DLNA. For that, I think that a VNET jail is the simplest (and possibly the only) way to go.
